### ISSUE TITLE
blocks added by 'Quick Add' are not fully copied to OmniFocus task

### ISSUE THREAD

**Issue by jmcmichael** [zhengyu-yang/logseq-plugin-omnifocus#2]
I often use LogSeq's 'Quick Add' feature from iOS's Share menu to store links in Journal pages. It adds blocks with the format

```
**HH:MM** [[quick-capture]]: https://domain.com/url/path
```

When I execute 'Send to OmniFocus', on these blocks, an item is created in OmniFocus, however its title and message only contain the timestamp portion of the block. For example, sending the block with the contents:

```
**06:52** [[quick capture]]:  https://tonsky.me/blog/centering/ - discussion of the painful difficulties centering elements using CSS #css
```

results in an OmniFocus item that looks like:
<img width="612" alt="Screenshot 2024-04-18 at 2 24 07 PM" src="https://github.com/zhengyu-yang/logseq-plugin-omnifocus/assets/132909/808a8cde-06d4-49a1-acec-d1b976d7199d">

Thank you for producing such a useful plugin!

**Comment by zhengyu-yang** [comment]
Fixed in 0.1.3
